name: parkingapp
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  syncfusion_flutter_gauges: ^20.3.50
  mqtt_client: ^9.7.2
  typed_data: ^1.3.1
  firebase_core: ^2.1.1
  firebase_database: ^10.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
     - family: Menlo
       fonts:
         - asset: assets/fonts/Menlo-Regular.ttf
